module 4 tasks 1,2
js-tasks-ru/vue-20200925-2_n-zbiranik pull request #7
Opened 2020-10-14 11:28 UTC by natkazb

2020-10-14 11:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между маршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```
```diff
ContentTabs
+ ContentTabs должен иметь обязательный параметр список tabs
+ ContentTabs должен рендерить список вкладок
- Активная вкладка должна иметь класс content-tabs__tab_active
```

2020-10-14 11:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между маршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```
```diff
ContentTabs
+ ContentTabs должен иметь обязательный параметр список tabs
+ ContentTabs должен рендерить список вкладок
- Активная вкладка должна иметь класс content-tabs__tab_active
```

2020-10-14 12:09 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между м��ршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```
```diff
ContentTabs
+ ContentTabs должен иметь обязательный параметр список tabs
+ ContentTabs должен рендерить список вкладок
+ Активная вкладка должна иметь класс content-tabs__tab_active
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-14 14:44 UTC, ShGKme requested changes
В обеих задачах требуются небольшие исправления...

2020-10-14 14:44 UTC, ShGKme commented on 04-SPA/01-ContentTabs/components/ContentTabs.vue
> +  },
Требуется использовать: https://router.vuejs.org/api/#active-class

Тогда класс активной ссылки будет не глобальный, а локально в этом приложении именно на этих ссылках.

2020-10-14 14:44 UTC, ShGKme commented on 04-SPA/02-ScrollBehavior/router/index.js
> +  }
Здесь не требуется `try`.
Если не известно, не является ли объект или его свойство null или undefined, то требуется либо писать обычные условия, либо использовать оператор `?.`.

Да, `try` тоже работает. Но здесь нет причин создавать исключение, нет причин выходить из основного потока выполнения.

Это достаточно грубая ошибка в коде, и, хотя она не связана с Vue.js, её потребуется исправить, чтобы задача была зачтена

2020-10-14 14:44 UTC, ShGKme commented on 04-SPA/02-ScrollBehavior/router/index.js
> -
Эта функция нужна в роутере, иначе она не работает...

2020-10-16 15:11 UTC, natkazb commented on 04-SPA/02-ScrollBehavior/router/index.js
> -
да, я случайно удалила, вернула все на место

2020-10-16 15:11 UTC, natkazb commented on 04-SPA/02-ScrollBehavior/router/index.js
> +  }
исправила

2020-10-16 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-16 15:24 UTC, natkazb commented on 04-SPA/01-ContentTabs/components/ContentTabs.vue
> +  },
исправила

2020-10-16 15:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-17 08:29 UTC, ShGKme approved these changes
Принято 👍

2020-10-17 08:29 UTC, ShGKme commented on 04-SPA/02-ScrollBehavior/router/index.js
> +  const saveScrollPositionFrom = from?.meta?.saveScrollPosition;
Поле meta всегда есть у маршрута, эту проверку можно не делать.

2020-10-17 08:30 UTC, ShGKme approved these changes

2020-10-17 08:30 UTC, merged