add solution for task 04-03
js-tasks-ru/vue-20200925-2_n-zbiranik pull request #8
Opened 2020-10-17 13:44 UTC by natkazb

2020-10-17 13:50 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 04-SPA/03-NotFound/__tests__/NotFound.test.js — добавлен
```

2020-10-23 14:37 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Layouts
+ TheHeader не дол��ен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-25 10:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-25 15:11 UTC, ShGKme requested changes
По задаче Layouts написал в Slack.

Остальные приняты

2020-10-25 15:11 UTC, ShGKme commented on 04-SPA/05-AuthPages/views/LoginPage.vue
> +  <form class="form" v-on:submit.prevent="login">
Лучше использовать короткую запись `@submit.prevent`

2020-10-25 15:11 UTC, ShGKme commented on 04-SPA/05-AuthPages/views/LoginPage.vue
> +    },
В целом так делать можно, но несколько избыточно

2020-10-25 15:11 UTC, ShGKme commented on 04-SPA/05-AuthPages/views/LoginPage.vue
> +      this.hasErrors.password = this.password ? false : true;
Запись `X ? false : true` эквивалентна `!X`

2020-10-26 13:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при сабмите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Работа с query параметрами
- Значение параметров должно соответствовать значениям query параметров в маршруте
- При изменении значения параметров должен меняться маршрут (push или query)
- При переходе на маршрут с другим query, должно обновлять соответствующие параметры
- Если какой-то параметр меняется на значение по умолчанию, его не должно быть в query
```
```diff
Layouts
+ TheHeader не должен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

2020-10-27 08:10 UTC, ShGKme requested changes
Задачи `NotFound`, `AuthPages` приняты.
Работа с query параметрами добавлена, но не решена.
По задаче `Layouts` требуется ещё несколько маленьких исправлений.

2020-10-27 08:10 UTC, ShGKme commented on 04-SPA/04-Layouts/components/TheHeader.vue
> +    <h1>Meetups</h1>
В качестве заголовка в вёрстке используется логотип, изображение.
https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/index.html#L18-L20

2020-10-27 08:10 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
> +  <main class="main">
`<main class="main">` присутствует на всех-всех страницах. Лучше перенести эту часть в `BaseLayout`.

2020-10-27 08:10 UTC, ShGKme commented on 04-SPA/04-Layouts/components/BaseLayout.vue
> +    <the-header class="header"/>
Классы `header` и `footer`, а также их стили относятся к компонентам шапки и подвала приложения. Лучше их перенести в соответствующие компоненты.

2020-10-28 15:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при сабмите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Работа с query параметрами
- Значение параметров должно соответствовать значениям query параметров в маршруте
- При изменении значения параметров должен меняться маршрут (push или query)
- При переходе на маршрут с другим query, должно обновлять соответствующие параметры
- Если какой-то параметр меняется на значение по умолчанию, его не должно быть в query
```
```diff
Layouts
+ TheHeader не должен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

2020-10-28 18:19 UTC, ShGKme requested changes
Задачи 3, 4, 5 приняты.
Требуется решить все добавленные задачи (6), чтобы PR был принят...

2020-11-04 16:02 UTC, natkazb commented
по 6 заданию никак не могу понять, почему не проходит 1-ый тест:
✕ Значение параметров должно соответствовать значениям query параметров в маршруте (50 ms)

2020-11-04 16:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при сабмите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Работа с query параметрами
+ При изменении значения параметров должен меняться маршрут (push или query)
+ При переходе на маршрут с другим query, должно обновлять соответствующие параметры
+ Если какой-то параметр меняется на значение по умолчанию, его не должно быть в query
- Значение параметров должно соответствовать значениям query параметров в маршруте
```
```diff
Layouts
+ TheHeader не должен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

2020-11-04 17:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при сабмите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Работа с query параметрами
+ При изменении значения параметров должен меняться маршрут (push или query)
+ При переходе на маршрут с другим query, должно обновлять соответствующие параметры
+ Если какой-то параметр меняется на значение по умолчанию, его не должно быть в query
- Значение параметров должно соответствовать значениям query параметров в маршруте
```
```diff
Layouts
+ TheHeader не должен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

2020-11-05 03:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-05 10:26 UTC, ShGKme approved these changes
Принято 👍

2020-11-05 10:27 UTC, merged